name: Submodule Changes CI

on:
  push:
    branches:
      - devops
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Check repository contents
      run: |
        ls -la
        cd deps
        ls -la
        cd ves-collector
        
        # Create the target directory inside the current workspace
        mkdir -p ./target/VESCollector-1.12.3-SNAPSHOT/
        
        # Copy the Dockerfile to the target directory
        cp ./src/docker/Dockerfile ./target/VESCollector-1.12.3-SNAPSHOT/
        
        # Change to the target directory and build the Docker image
        cd ./target/VESCollector-1.12.3-SNAPSHOT/
        docker build -t sknrao/ves-collector:1.12.3 .
        
    # - name: Build Docker Image
    #   run: |
    #     docker build -t sknrao/ves-collector:1.12.3 .
