name: Build Docker Image

on:
  push:
    branches:
      - 'devops'
      - '**'  # This will match any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # This will clone the submodules

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'maven'

    - name: Update submodule to latest commit
      run: |
        git submodule update --init --recursive
        cd ves-collector
        git fetch
        git checkout $(git rev-parse HEAD)
        cd ..

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -f ves-collector/src/docker/Dockerfile -t your-image-name:latest .
#test
