name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      submodule_ref:
        description: 'Submodule reference (e.g., branch, tag, or commit hash)'
        required: true
        default: 'devops'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # This will clone the submodules

    - name: Update submodule to specified ref
      run: |
        git submodule update --init --recursive
        cd ves-collector
        git fetch
        git checkout ${{ github.event.inputs.submodule_ref }}
        cd ..

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -f ves-collector/src/docker/Dockerfile -t your-image-name:latest .
